name: Build and Push Docker image

on:
  push:
    branches: ["master"]   # Change to your main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # Required for GHCR

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy from main branch
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          script: |
            set -e
            cd /srv/apps/${{ github.event.repository.name }}
            # Pull latest repository changes (THIS WAS MISSING!)
            git pull origin master

            docker compose pull
            docker compose up -d --remove-orphans --force-recreate
            docker image prune -f
            # Verify deployment

            echo "Deployment completed successfully!"
            docker ps | grep kenthdev-cms